#!/bin/bash

# Remove existing file (if any)
if [ -f ~/x ]; then
    rm ~/x
fi

# Install termux-am
echo "Installing termux-am"
pkg install termux-am -y &>/dev/null

# Set up storage
termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Storage permission denied"
    fi
    sleep 3
done

# Install necessary packages
echo "Installing termux packages"
pkg install x11-repo pulseaudio xwayland wget tsu root-repo patchelf p7zip xorg-xrandr ncurses-utils hashdeep termux-x11-nightly -y &>/dev/null

# Remove previous glibc if exists
if [ -e $PREFIX/glibc ]; then
    echo -n "Removing previous glibc. Continue? (Y/n) "
    read i
    if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
        rm -rf $PREFIX/glibc
    else
        exit 1
    fi
fi

# Install wget if not installed
if ! command -v wget &> /dev/null; then
    echo "Installing wget..."
    pkg install wget -y &>/dev/null
fi

# Download Windows 10 ISO
echo "Downloading Windows 10 ISO"
wget https://go.microsoft.com/fwlink/p/?LinkID=2195404&clcid=0x409&culture=en-us&country=US -O ~/win10.iso

# Run QEMU with Windows 10 ISO and enable mouse and keyboard input
echo "Starting Windows 10 installation"
qemu-system-x86_64 -cdrom ~/win10.iso -m 4G -boot d -usb -device usb-tablet

# Cleanup: Remove the ISO file after installation
rm ~/win10.iso

# Install WinEonix
echo "Installing WinEonix"

function wget-git-q {
    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
    return $?
}

echo "Updating package manager"
mkdir -p $PREFIX/glibc/opt/package-manager/installed

echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token

. $PREFIX/glibc/opt/package-manager/token
if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
    echo "Download failed"
    exit 1
fi
. $PREFIX/glibc/opt/package-manager/package-manager
sync-all

sync-package wine-ge-custom-8-25

# Change emulator name to WinEonix
sed -i 's/mobox/WinEonix/g' $PREFIX/glibc/opt/package-manager/package-manager

ln -sf $PREFIX/glibc/opt/scripts/WinEonix $PREFIX/bin/WinEonix
echo "To start - type \"WinEonix\""
